name: project_ai
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit
  - h5py
  - hdf5
  - jupyter
  - nltk
  - numpy
  - pandas
  - pip
  - python=3.7.3
  - pytorch
  - scipy
  - seaborn
  - setuptools
  - spyder
  - tensorboard
  - pip:
    - allennlp
    - tensorboardx
    - torchtext
